name: deploy-all-infra

concurrency:
  group: infra-global
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - stg
          - prod

permissions:
  contents: read

##########################################################
# STEP 1 — NETWORK
##########################################################
jobs:

  network:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: azure/network

    outputs:
      exitcode: ${{ steps.plan.outputs.exitcode }}
      destroy: ${{ steps.detect.outputs.destroy }}

    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - name: Configure Git credentials
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Init
        run: tofu init -backend-config="key=network-${{ github.event.inputs.environment }}.tfstate"

      - name: Plan
        id: plan
        run: |
          set +e
          tofu plan \
            -var-file=env/${{ github.event.inputs.environment }}.tfvars \
            -out=tfplan \
            -detailed-exitcode
          echo "exitcode=$?" >> $GITHUB_OUTPUT
          set -e

      - name: Detect Destroy
        id: detect
        if: steps.plan.outputs.exitcode == '2'
        run: |
          tofu show -json tfplan > plan.json
          if jq -e '.resource_changes[]? | select(.change.actions | index("delete"))' plan.json > /dev/null; then
            echo "destroy=true" >> $GITHUB_OUTPUT
          else
            echo "destroy=false" >> $GITHUB_OUTPUT
          fi

  network_apply:
    needs: network
    if: needs.network.outputs.exitcode == '2'
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: azure/network

    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - name: Configure Git credentials
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Init
        run: tofu init -backend-config="key=network-${{ github.event.inputs.environment }}.tfstate"

      - name: Apply
        run: tofu apply -auto-approve -var-file=env/${{ github.event.inputs.environment }}.tfvars

##########################################################
# STEP 2 — SECURITY
##########################################################

  security:
    #needs: network_apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: azure/security

    outputs:
      exitcode: ${{ steps.plan.outputs.exitcode }}
      destroy: ${{ steps.detect.outputs.destroy }}

    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - name: Configure Git credentials
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Init
        run: tofu init -backend-config="key=security-${{ github.event.inputs.environment }}.tfstate"

      - name: Plan
        id: plan
        run: |
          set +e
          tofu plan \
            -var-file=env/${{ github.event.inputs.environment }}.tfvars \
            -out=tfplan \
            -detailed-exitcode
          echo "exitcode=$?" >> $GITHUB_OUTPUT
          set -e

      - name: Detect Destroy
        id: detect
        if: steps.plan.outputs.exitcode == '2'
        run: |
          tofu show -json tfplan > plan.json
          if jq -e '.resource_changes[]? | select(.change.actions | index("delete"))' plan.json > /dev/null; then
            echo "destroy=true" >> $GITHUB_OUTPUT
          else
            echo "destroy=false" >> $GITHUB_OUTPUT
          fi

  security_apply:
    needs: security
    if: needs.security.outputs.exitcode == '2'
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: azure/security

    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - name: Configure Git credentials
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Init
        run: tofu init -backend-config="key=security-${{ github.event.inputs.environment }}.tfstate"

      - name: Apply
        run: tofu apply -auto-approve -var-file=env/${{ github.event.inputs.environment }}.tfvars

##########################################################
# STEP 3 — COMPUTE
##########################################################

  compute:
    #needs: security_apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: azure/compute

    outputs:
      exitcode: ${{ steps.plan.outputs.exitcode }}
      destroy: ${{ steps.detect.outputs.destroy }}

    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - name: Configure Git credentials
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Init
        run: tofu init -backend-config="key=compute-${{ github.event.inputs.environment }}.tfstate"

      - name: Plan
        id: plan
        run: |
          set +e
          tofu plan \
            -var-file=env/${{ github.event.inputs.environment }}.tfvars \
            -out=tfplan \
            -detailed-exitcode
          echo "exitcode=$?" >> $GITHUB_OUTPUT
          set -e

      - name: Detect Destroy
        id: detect
        if: steps.plan.outputs.exitcode == '2'
        run: |
          tofu show -json tfplan > plan.json
          if jq -e '.resource_changes[]? | select(.change.actions | index("delete"))' plan.json > /dev/null; then
            echo "destroy=true" >> $GITHUB_OUTPUT
          else
            echo "destroy=false" >> $GITHUB_OUTPUT
          fi

  compute_apply:
    needs: compute
    if: needs.compute.outputs.exitcode == '2'
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: azure/compute

    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - name: Configure Git credentials
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Init
        run: tofu init -backend-config="key=compute-${{ github.event.inputs.environment }}.tfstate"

      - name: Apply
        run: tofu apply -auto-approve -var-file=env/${{ github.event.inputs.environment }}.tfvars